### ISSUE TITLE
Create a Basic Skeleton

### ISSUE THREAD

**Issue by HimeshNayak** [HimeshNayak/Hackathons-Portfolio-Web#1]
Create a basic Skeleton of the website preferably before **Sunday, 14 June 2020** so that backend work can be started by the backend team.

Following web pages / sections are to be made _Also if you want to add other things as per your choice, please do_ :
- [x] Home page - containing header image and footer and sections for about our Group, Our Aim, etc.
- [x] Portfolio Page - containing name/pics of all the members as footer and a section to display the work of the member selected.
- [ ] Works of our team as a whole.
- [x] Contact us / Join Us.

**Comment by HellVolhard07** [comment]
Home page prototype done.

**Comment by HellVolhard07** [comment]
Added portfolio page prototype

**Comment by HimeshNayak** [comment]
First Complete Frontend Prototype Made By @HellVolhard07 and @Kshitij-24 
Except for the Works Done Page, which can be made by @shubham-rawal 

Now the Backend Team can start working on the prototype. Will provide a detailed issue about it.
