### ISSUE TITLE
Work left for Phase 1

### ISSUE THREAD

**Issue by HimeshNayak** [HimeshNayak/Hackathons-Portfolio-Web#10]
1. 
- [x] Frontend - Single Portfolio Page - (sections) image, name, position, skills, links to projects, certificates, contact (mail, github)
- [x] Works Done Page - (sections) GDs/Meets/Webinars - Done in past and upcoming, Projects done till now (little bit info about the project, names of the developers and link of repo/hosting)
- [x] Join Us Form (Text from Google form that I gave to you)
- [x] Portfolio Card - image, name and position, hover: intro, Learn more button

2. 
- [x] Backend - Push data from contact form and join us form to the database

If I missed out anything, do tell. And Please give your Suggestions too.

**Comment by HimeshNayak** [comment]
Firebase Backend Added to master branch

**Comment by HellVolhard07** [comment]
Works done prototype page done

**Comment by HimeshNayak** [comment]
All work in this issue is done!!!
