### ISSUE TITLE
Add Backend to the Frontend Prototype

### ISSUE THREAD

**Issue by HimeshNayak** [HimeshNayak/Hackathons-Portfolio-Web#6]
Following things are to be done by the Backend Team

- [x] Add the frontend to node 
- [x] Add Firebase Realtime Database to store the contact us form by the users
- [x]  Add Works Done Backend to the page

Also please suggest what else can be done

**Comment by RGTechno** [comment]
Frontend Attached to node server...

**Comment by HimeshNayak** [comment]
Added Firebase Backend to JoinUs and ContactUs forms, which was made by @harshgoyal7065

**Comment by HimeshNayak** [comment]
Added works done statically
Will connect it to firestore in next phase
