### ISSUE TITLE
Completing frontend

### ISSUE THREAD

**Issue by HimeshNayak** [HimeshNayak/Hackathons-Portfolio-Web#8]
Here are some Bugs in the Frontend :

- [x] The Card overlays the Bavigation Bar 
![Imgur](https://i.imgur.com/cvyP8q6.png)

- [x] Mobile Compatibility Issue
![Imgur](https://i.imgur.com/oYDS7pt.png) 

Please try to work on these... 

If anyone finds any other bug or enhancements that can be done, please comment

**Comment by RGTechno** [comment]
The Card overlays the Navigation Bar -> bug resolved

**Comment by HimeshNayak** [comment]
The issue is still not fixed. Also when the screen size changes the menu bar should change to a side bar with hamburger icon.
@RGTechno @Arsenic-ATG Do look into it

**Comment by HellVolhard07** [comment]
2 pages are now responsive i.e. home and portfolio + hamburger icon added

**Comment by HellVolhard07** [comment]
- [ ] Extra padding
Padding of each page needs to be corrected.

- [ ] About section
About page should be added in index.html as a section to that when clicked, it scrolls down to the section instead of redirecting.

- [ ] Responsive
Make the rest pages responsive as well.

**Comment by HellVolhard07** [comment]
Footer section corrected.

**Comment by HellVolhard07** [comment]
- [ ] Line below the header

- [ ] Portfolio cards should close when clicked anywhere else on the screen

- [ ] CSS on submit buttons
